Machine structs
filipe1417/zepa-machine pull request #5
Opened 2024-09-06 03:17 UTC by filipe1417

2024-09-07 12:31 UTC, thiagomanel commented on zepa.go
> +type GeneralRegisters struct {
@filipe1417 I think having different struct for registers (GeneralRegisters and SpecialRegisters) is good for ease reading the code but will make it hard to decode the instructions latter.

An alternative is to have a kind of enum (e.g const of keys using iota) called Registers (grouping all kind of registers). We do not need to change this now. Instead, you can add a refactor comment in the code to do it latter when we start coding the fetch-decode-execute loop

2024-09-07 12:35 UTC, thiagomanel commented on zepa.go
> +type Memory struct {
I think this struct is not necessary. Instead, in the `Machine struct` add the memory field as:

`memory    byte[]`

it is simple and also solve a problem of supporting machines larger than 1024 bytes of memory (since in your struct the memory size if fixed)

2024-09-07 12:36 UTC, thiagomanel commented on zepa.go
> +}
add a constructor function for the machine struct. something like:

`func NewMachine(memoryBytes int) *Machine`

this function should init the memory and the register values.

2024-09-07 12:37 UTC, thiagomanel requested changes
thanks @filipe1417, we are in the right direction. see my comments

2024-09-08 05:27 UTC, filipe1417 commented on zepa.go
> +type GeneralRegisters struct {
I've decided to make the changes now to organize the rest of the code around it. Thanks for the suggestion

2024-09-08 05:28 UTC, filipe1417 commented
Restructured the code, thanks for the guidance

2024-09-08 11:35 UTC, thiagomanel commented on zepa.go
> +
@filipe1417, I'm not sure we need this numberOfRegisters

2024-09-08 11:45 UTC, thiagomanel requested changes
almost done

2024-09-08 11:45 UTC, thiagomanel commented on zepa.go
> +	registers [numberOfRegisters]Register
maybe, replace by a map and  make the map in the newMachine func

2024-09-10 23:55 UTC, thiagomanel approved these changes
lgtm

2024-09-10 23:55 UTC, merged